export const systemSignals = [
  {
    label: 'Offline sync',
    value: 'Ready',
    detail: 'Local server fallback and queued updates prepared',
  },
  {
    label: 'Audit trail',
    value: 'Live',
    detail: 'Every clinical action is timestamped and attributable',
  },
  {
    label: 'Exchange layer',
    value: 'FHIR-ready',
    detail: 'Designed for DHIS2, MaHIS, LOINC, and DICOM growth',
  },
];

export const roles = [
  {
    id: 'receptionist',
    title: 'Receptionist',
    navLabel: 'Reception',
    user: 'Tadala Mbewe',
    focus: 'Registration, appointments, patient flow, and billing touchpoints',
    tag: 'Front desk',
    accent: '#16aeb8',
    metrics: [
      { label: 'Checked in today', value: '42', detail: '9 walk-ins, 33 booked' },
      { label: 'Fast-track flags', value: '5', detail: 'Emergency and priority triage' },
      { label: 'Potential duplicates', value: '3', detail: 'MPI merge review needed' },
      { label: 'Unpaid invoices', value: '18', detail: 'Billing follow-up queue' },
    ],
    actions: [
      'Register patients with hospital number, National ID, guardian, address, village, TA, district, and consent status.',
      'Book appointments, handle walk-ins, manage check-in and check-out, and create follow-up visits.',
      'Prioritize queues, flag emergencies, route referrals, and capture payment references.',
    ],
    worklist: [
      { patient: 'Chikondi Banda', context: 'New outpatient profile', status: 'Needs triage', priority: 'High' },
      { patient: 'Amina Osman', context: 'Possible duplicate hospital number', status: 'MPI review', priority: 'Medium' },
      { patient: 'Mphatso Phiri', context: 'Missed renal clinic appointment', status: 'Callback due', priority: 'Medium' },
      { patient: 'John Phiri', context: 'Lab and pharmacy bill pending', status: 'Payment check', priority: 'Low' },
    ],
    modules: [
      'Patient registration',
      'Master patient index',
      'Appointments and queue',
      'Referral routing',
      'Billing and receipts',
      'SMS reminder concept',
    ],
    alerts: [
      'Consent missing for two research-participant profiles.',
      'One emergency registration still needs full demographic completion.',
      'Duplicate detection suggests a merge review before consultation.',
    ],
  },
  {
    id: 'nurse',
    title: 'Nurse',
    navLabel: 'Nurse',
    user: 'Grace Chirwa',
    focus: 'Triage, observations, nursing notes, medication administration, and handover',
    tag: 'Ward and triage',
    accent: '#0f9ca5',
    metrics: [
      { label: 'Vitals due', value: '16', detail: '6 repeat observations' },
      { label: 'Abnormal escalations', value: '4', detail: 'Early warning triggers' },
      { label: 'Medication rounds', value: '22', detail: 'MAR checks remaining' },
      { label: 'Handover items', value: '9', detail: 'Ward continuity notes' },
    ],
    actions: [
      'Capture triage category, vital signs, pain score, pregnancy status, blood glucose, and GCS where applicable.',
      'Document nursing assessments, care plans, wound care, patient education, and discharge counselling.',
      'Escalate abnormal observations and maintain medication administration records and ward handover.',
    ],
    worklist: [
      { patient: 'Ruth Nyirenda', context: 'BP 178/104 and headache', status: 'Escalate doctor', priority: 'High' },
      { patient: 'Peter Moyo', context: 'Post-op wound review', status: 'Dressing due', priority: 'Medium' },
      { patient: 'Elina James', context: 'Paediatric fever trend', status: 'Repeat vitals', priority: 'High' },
      { patient: 'Felix Nkhata', context: 'Discharge counselling', status: 'Education note', priority: 'Low' },
    ],
    modules: [
      'Triage',
      'Vital signs and charts',
      'Nursing care plans',
      'Medication administration',
      'Fall and pressure risk',
      'Handover and escalation',
    ],
    alerts: [
      'Two paediatric observations are outside age-adjusted ranges.',
      'One medication dose was held and needs provider acknowledgement.',
      'Pressure sore risk assessment is overdue for one admitted patient.',
    ],
  },
  {
    id: 'doctor',
    title: 'Doctor',
    navLabel: 'Doctor',
    user: 'Dr. Kelvin Banda',
    focus: 'Clinical documentation, diagnosis, orders, prescribing, result review, and discharge planning',
    tag: 'Provider',
    accent: '#188fbd',
    metrics: [
      { label: 'Patients to review', value: '21', detail: '7 new, 14 follow-up' },
      { label: 'Results to sign', value: '8', detail: '2 critical acknowledgements' },
      { label: 'Orders pending', value: '13', detail: 'Lab, imaging, and pharmacy' },
      { label: 'Discharge summaries', value: '5', detail: 'Awaiting final signature' },
    ],
    actions: [
      'Record H&P, admission notes, progress notes, procedure notes, medication reconciliation, and clinical decisions.',
      'Enter diagnoses, care plans, prescriptions, lab orders, imaging requests, referrals, and follow-up plans.',
      'Review and acknowledge results, update care plans, and complete discharge summaries with audit signatures.',
    ],
    worklist: [
      { patient: 'Mary Tembo', context: 'Critical potassium result', status: 'Acknowledge now', priority: 'High' },
      { patient: 'Davies Kamanga', context: 'Chest X-ray report posted', status: 'Review imaging', priority: 'Medium' },
      { patient: 'Thandiwe Zulu', context: 'New outpatient encounter', status: 'Document H&P', priority: 'Medium' },
      { patient: 'Isaac Mwale', context: 'Ward discharge ready', status: 'Summary due', priority: 'Low' },
    ],
    modules: [
      'Clinical notes',
      'Diagnosis and coding',
      'Order entry',
      'Prescribing safety',
      'Result acknowledgement',
      'Discharge planning',
    ],
    alerts: [
      'One prescription has a renal dose adjustment warning.',
      'Critical laboratory result requires acknowledgement before closing encounter.',
      'Follow-up appointment missing for a chronic kidney disease patient.',
    ],
  },
  {
    id: 'pharmacist',
    title: 'Pharmacist',
    navLabel: 'Pharmacy',
    user: 'Linda Ngalande',
    focus: 'Medication safety, dispensing, stock status, controlled medicines, and pharmacy workload',
    tag: 'Medication safety',
    accent: '#12a37f',
    metrics: [
      { label: 'Prescriptions waiting', value: '31', detail: '6 priority discharge meds' },
      { label: 'Safety checks', value: '7', detail: 'Interactions and allergies' },
      { label: 'Low-stock items', value: '11', detail: '3 below reorder level' },
      { label: 'Controlled meds', value: '4', detail: 'Register reconciliation' },
    ],
    actions: [
      'Review electronic prescriptions for dose, route, frequency, duration, allergies, duplicates, and interactions.',
      'Update dispensing status, medication history, stock availability, batch, expiry, and controlled-medicine logs.',
      'Feed pharmacy workload, stock alerts, and medication administration linkage back to clinical teams.',
    ],
    worklist: [
      { patient: 'Mercy Nkhoma', context: 'Penicillin allergy on file', status: 'Verify alternative', priority: 'High' },
      { patient: 'Brian Lungu', context: 'Paediatric dosing check', status: 'Dose review', priority: 'High' },
      { patient: 'Agnes Mvula', context: 'Discharge medicines', status: 'Dispense pack', priority: 'Medium' },
      { patient: 'Ward A stock', context: 'Ceftriaxone below reorder level', status: 'Restock request', priority: 'Medium' },
    ],
    modules: [
      'Prescription queue',
      'Allergy and interaction checks',
      'Dispensing records',
      'Stock and expiry',
      'Controlled medicines',
      'Pharmacy analytics',
    ],
    alerts: [
      'Duplicate therapy warning on one active prescription.',
      'Three medications expire within 30 days.',
      'Controlled medicines reconciliation is due before end of shift.',
    ],
  },
  {
    id: 'laboratory',
    title: 'Laboratory Technician',
    navLabel: 'Laboratory',
    user: 'Patrick Kalua',
    focus: 'Order receipt, specimen tracking, result entry, verification, quality control, and turnaround time',
    tag: 'Diagnostics',
    accent: '#2b7fc3',
    metrics: [
      { label: 'Samples to receive', value: '24', detail: 'Barcode labels pending' },
      { label: 'Tests processing', value: '38', detail: 'CBC, chemistry, malaria RDT' },
      { label: 'Critical results', value: '2', detail: 'Requires clinician alert' },
      { label: 'Median TAT', value: '48m', detail: 'Target under 60m' },
    ],
    actions: [
      'Receive orders, track specimen type, sample collection status, barcode labels, and referral lab linkage.',
      'Enter, verify, approve, and publish results with abnormal flags and critical result alerts.',
      'Maintain quality control notes, reagent inventory, workload dashboard, and LOINC-ready result mapping.',
    ],
    worklist: [
      { patient: 'Mary Tembo', context: 'Critical potassium 6.4 mmol/L', status: 'Notify doctor', priority: 'High' },
      { patient: 'Samuel Kaphiri', context: 'Sample not received', status: 'Call collection', priority: 'Medium' },
      { patient: 'HIV clinic batch', context: 'External referral tests', status: 'Dispatch log', priority: 'Medium' },
      { patient: 'QC bench', context: 'Chemistry control run', status: 'Document QC', priority: 'Low' },
    ],
    modules: [
      'Order receipt',
      'Specimen tracking',
      'Result entry',
      'Verification and approval',
      'Critical alerts',
      'QC and reagent inventory',
    ],
    alerts: [
      'Critical result alert has not yet been acknowledged by provider.',
      'Two samples are past expected collection time.',
      'Reagent stock for creatinine is below minimum threshold.',
    ],
  },
  {
    id: 'administrator',
    title: 'Administrator',
    navLabel: 'Admin',
    user: 'Martha Soko',
    focus: 'Users, departments, governance, audit, backups, revenue, and system operations',
    tag: 'Governance',
    accent: '#5b8f74',
    metrics: [
      { label: 'Active users', value: '86', detail: '12 roles across services' },
      { label: 'Audit events', value: '1.8k', detail: 'Last 24 hours' },
      { label: 'Backup status', value: '02:00', detail: 'Last successful checkpoint' },
      { label: 'Open incidents', value: '6', detail: '2 downtime reports' },
    ],
    actions: [
      'Manage user accounts, role-based access, department configuration, service catalogue, and facility settings.',
      'Monitor audit trails, access logs, data governance, backups, downtime reporting, and incident response.',
      'Review usage, revenue, unpaid bills, change control, and readiness for secure national integration.',
    ],
    worklist: [
      { patient: 'RBAC request', context: 'New pharmacy intern access', status: 'Approve role', priority: 'Medium' },
      { patient: 'Backup monitor', context: 'Nightly sync completed', status: 'Verify report', priority: 'Low' },
      { patient: 'Billing review', context: 'Unpaid inpatient invoices', status: 'Revenue report', priority: 'Medium' },
      { patient: 'Incident log', context: 'Ward Wi-Fi outage', status: 'Downtime review', priority: 'High' },
    ],
    modules: [
      'User accounts',
      'Role-based access',
      'Facility configuration',
      'Audit and logs',
      'Backup monitoring',
      'Governance dashboard',
    ],
    alerts: [
      'Two users have temporary elevated access expiring today.',
      'Downtime drill checklist is due for nursing and laboratory teams.',
      'Monthly data governance report needs final sign-off.',
    ],
  },
];
